### ISSUE TITLE
Initial draws from prior are identical

### ISSUE THREAD

**Issue by ryants** [LoLab-VU/PyDREAM#2]
When not specifying the "start" argument in the run_dream function, the initial parameters for each chain are identical.  I assume they should be distinct?

**Comment by eshockley** [comment]
Thanks for pointing this out. There was an issue with the random state of the scipy/numpy generator not being changed for child processes that I had missed. This should be fixed with the latest commits to master. Let me know if there are still issues.

**Comment by ryants** [comment]
Seems to work now.  Thanks for the quick turnaround!
