### ISSUE TITLE
Running chains in parallel

### ISSUE THREAD

**Issue by jyangfsu** [LoLab-VU/PyDREAM#24]
I am trying to like PyDREAM with my own program. The program reads the parameters in the input file and then generate a output file to disk. I need to read data from the output file and then calculate the likelihood. The problem is that PyDREAM always runs chains in parallel. This would cause problem when parallel runs try to write the output values to the same  file. Is it possible to disable the parallel run even if one more chains are used, say nchains=5?

Hope I have made myself clear. Thank you.

**Comment by ortega2247** [comment]
Hi,

Thank you for using PyDREAM. Unfortunately the parallel chains are hardcoded in the pydream code, so currently it is not possible to disable the parallel runs. You are more than welcome to submit a PR that implements this.
