### ISSUE TITLE
ValueError arises when using uniform priors

### ISSUE THREAD

**Issue by ryants** [LoLab-VU/PyDREAM#3]
When I attempt to use a list of SampledParam objects with uniform distributions, I get the following error from inside the Dream object:

``ValueError: zero-dimensional arrays cannot be concatenated``

I initialized the parameters as seen in https://gist.github.com/ryants/b0da3eea4d6d515183fca8476916365b

**Comment by eshockley** [comment]
I've just pushed a commit that should fix this -- PyDREAM tries to reflect points back in the bounds when using priors with hard boundaries (like uniform) but there was a bug in that code. With the latest changes I'm able to run your example.

**Comment by ryants** [comment]
Thanks!
